name: Test Build

on:
  workflow_dispatch:
  push:
    branches: [ devel ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - run: echo "🔨 Testing build..."
    - run: mvn --version
    - run: java -version
    - run: mvn clean compile -DskipTests=true --batch-mode
    - run: echo "✅ Build test completed!"
